### ISSUE TITLE
Common keyboard shortcuts do not work

### ISSUE THREAD

**Issue by flesser** [owncloud/documents#321] opened 2014-08-01 08:03 UTC
Common keyboard shortcuts for text editing seem to be unavailable, thus disrupting the accustomed document editing workflow. Especially I'm missing:
Ctrl+Z (undo)
Ctrl+C (copy)
<s>Ctrl+V (paste)</s>
Ctrl+X (cut)

Tested in: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0

**Comment by pascalBokBok** [comment] 2015-03-11 17:44
So there is no undo in owncloud documents?

**Comment by zsteinmetz** [comment] 2015-03-17 10:01
No, there is no undo feature yet, neither as button nor shortcut ... this is a pretty basic feature which really should get some attention!

**Comment by pascalBokBok** [comment] 2015-03-17 10:08
strange because it works fine in WebODF's demo which I thought  was the base.
http://www.webodf.org/demo/ci/wodotexteditor-0.5.6/localeditor.html

**Comment by zsteinmetz** [comment] 2015-03-17 10:12
right. seems like ownCloud uses a pared-down version.

**Comment by VicDeo** [comment] 2015-06-11 16:22
Undo/Redo in collab mode https://github.com/kogmbh/WebODF/blob/master/programs/editor/wodocollabtexteditor.js#L183

**Comment by VicDeo** [comment] 2015-06-16 14:13
Fixed with https://github.com/owncloud/documents/issues/492
Tested with Firefox 38.0.1

**Closed by VicDeo** 2015-06-16 14:13 UTC

**Comment by pascalBokBok** [comment] 2015-06-16 14:16
:smile:

**Comment by TomaszWaszczyk** [comment] 2016-06-15 17:54
There is a way to change CTRL + C shortcut in ownCloud Documents ? In Polish there is a letter "C" and it is just a shortcut for it: CTRL + C....

**Comment by mdigit5** [comment] 2017-02-27 20:52
I realize the issue is very old - sorry if this is not the correct place to post this. Please let me know.

The CTRL + Z for undo doesn't work for me. I've tested in Chrome Version 56.0.2924.87, Firefox 51.0.1, and IE 11.0.9600.18537.

ownCloud version is 9.1.3 (stable)
Documents App version is 0.13.1

As it is, there is no way out of a bad edit. You can't undo, and you can't exit without saving. Although it's a very neat App, it's pretty tough to use it in the real world with Undo (and exit without saving).
