### ISSUE TITLE
Editing documents in Owncloud 8.2.1 / Nginx / php5-fpm

### ISSUE THREAD

**Issue by 31337** [owncloud/documents#588] opened 2015-11-19 21:53 UTC
### Steps to reproduce
1. Log in to Owncloud 8.2.1
2. Right click on a document (.odt / .docx) and chose "edit"

### Expected behaviour
The documents-app should be opened loading the clicked on document

### Actual behaviour
You will be redirected to the files (starting) screen of Owncloud,
in my case https://***REMOVED SENSITIVE VALUE***/index.php/apps/files/#615

### Server configuration
**Operating system**:
Debian 8.2

**Web server:**
nginx/1.9.7

**Database:**
MariaDB 10.0.22-0+deb8u1

**PHP version:**
5.6.14+dfsg-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
8.2.1

**Updated from an older ownCloud or fresh install:**
Updated from 8.2.0

**List of activated apps:**
  - activity: 2.1.3
  - documents: 0.11.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1

**The content of config/config.php:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/ocdatastore\/***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/tmp\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chromium 46.0.2490.71
Firefox 42

**Operating system:**
Debian Stretch

#### Web server error log
(This is what happens right after you click on "edit" (see above):
***REMOVED SENSITIVE VALUE*** - - [19/Nov/2015:22:05:37 +0100] "GET /index.php/apps/documents HTTP/2.0" 302 633 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36" "-"
***REMOVED SENSITIVE VALUE*** - - [19/Nov/2015:22:05:37 +0100] "GET /index.php/apps/files/ HTTP/2.0" 200 30716 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36" "-"
***REMOVED SENSITIVE VALUE*** - - [19/Nov/2015:22:05:38 +0100] "GET /index.php/core/js/oc.js?v=d345cdfe8ca8361d8fdd3eb54e556c5c HTTP/2.0" 200 2666 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36" "-"
***REMOVED SENSITIVE VALUE*** - - [19/Nov/2015:22:05:39 +0100] "GET /index.php/avatar/as/128 HTTP/2.0" 200 619 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36" "-"
***REMOVED SENSITIVE VALUE*** - - [19/Nov/2015:22:05:39 +0100] "GET /index.php/apps/documents/ajax/mimes.php HTTP/2.0" 200 576 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36" "-"

#### ownCloud log (data/owncloud.log)
Log is empty

#### Browser log
Not available / necessary

BTW: 
- Nginx is configured as in 
https://doc.owncloud.org/server/8.2/admin_manual/installation/nginx_configuration.html

- Opening the documents-app from the Owncloud menu works, you can edit .docx and .odt files there!

**Comment by VicDeo** [comment] 2015-11-19 21:55
@31337 thanks for the detailed report! :ice_cream: 
Since this is an exact duplicate of https://github.com/owncloud/documents/issues/564 let's continue there

**Closed by VicDeo** 2015-11-19 21:55 UTC
