### ISSUE TITLE
no workie with 8.1

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/documents#502] opened 2015-07-05 10:21 UTC
The final 8.1 tarballs allow installing Documents and looking at the files overview, but when I click to open a file, I get a spinner-of-death and this in the logs:

```
Error 	PHP 	Class 'OC_FileProxy' not found at /srv/www/htdocs/owncloud/apps/documents/lib/genesis.php#90 	2015-07-05T10:17:58+00:00 
```

On openSUSE Tumbelweed (latest stable version of everything - Apache, mysql, php)

@VicDeo

**Comment by Friendbg** [comment] 2015-07-07 18:52
Hi, just updated to 8.1 and had the same problem : PHP Fatal error:  Class 'OC_FileProxy' not found in /var/www/owncloud/apps/documents/lib/genesis.php on line 90

I hope it will be fixed asap. 
Thank you

**Comment by nkinkade** [comment] 2015-07-08 00:04
I'm seeing the same thing.  It looks like commit fa1826a may not have made it into 8.1 release somehow.  Applying that commit to my clean checkout of tags/v8.1.0 seems to have fixed the issue.  (note: I'm running from a git clone, not from a downloaded archive or package).

**Comment by RealRancor** [comment] 2015-07-08 07:31
> I'm seeing the same thing. It looks like commit fa1826a may not have made it into 8.1 release somehow.

The documents app is not included in the 8.1 release so the version containing that fix still needs to be published on https://apps.owncloud.com/content/show.php/Documents?content=168711

**Comment by Friendbg** [comment] 2015-07-08 08:13
Thanks nkinkade and RealRancor, just updated my documents to https://github.com/owncloud/documents/archive/v8.1RC2.tar.gz and all works fine! :) I hope they update the official app soon.

**Comment by dhsc19** [comment] 2015-07-08 17:15
I've installed the the contents of v8.1RC2.tar.gz over the existing documents directory.  Owncloud went into maintenance mode and said it updated documents to version 0.10.0.  Now when I try to open a document, I get the format options bar, but still only the spinning indicator where the document should be.

**Comment by Lebernd** [comment] 2015-07-08 19:47
@dhsc19 https://github.com/owncloud/documents/issues/502#issuecomment-119668256 same here.
When I try to quit I get an alert:
```
ASSERTION FAILED: 
editorSession should exist here.
```

**Comment by rodrigo102920** [comment] 2015-07-08 20:55
Same issue as Lebernd here.

**Comment by jospoortvliet** [comment] 2015-07-09 07:18
We'll come with a release soon, hopefully today.

**Comment by AisoPlee** [comment] 2015-07-09 09:13
I confirm this issue. Could it be related to  #473?

**Comment by jospoortvliet** [comment] 2015-07-09 10:45
The version in the app store, 0.9.0, is the old one and does not work with 8.1. The latest version, only to be found on https://github.com/owncloud/documents/releases is 0.10.0 and DOES work with ownCloud 8.1 - but you'll have to install it manually until it is properly released on the app store. As I said, we'd like to do that asap, today hopefully, but the Documents author @VicDeo is on holiday.

However, you can manually grab the 8.1.0 tarball from https://github.com/owncloud/documents/releases and it'll work.

Note that after installation, click on the cloud (or go to the Files app) and the upgrade will run. After that - you should see this in the app section:
![statistics june 22 2016](https://cloud.githubusercontent.com/assets/551757/8593471/4fb9c802-2638-11e5-8087-f7147ea97b81.png)

and the app will work.

**Comment by shaneonabike** [comment] 2015-07-09 12:54
Hmmm I tried both the 8.1 and 81RC2 releases, which performed the upgrade but is still get the spinning wheel :/

I don't see anything in my log files though (even with debug on). Let me know if I can help at all.

**Comment by jospoortvliet** [comment] 2015-07-09 14:33
@shaneonabike so you:

* removed the current Documents app (the broken one)
* downloaded version 8.1 from https://github.com/owncloud/documents/releases
* put it in the right folder with the right permissions,
* load the file app
* get the blue screen that ownCloud is updating (let it do that)
* go to the documents app and it just spins forever

Correct?
If so, could you see if applying https://github.com/owncloud/documents/commit/fa1826afdc911b0e25109ec7295f457d874eddf0 fixes it?

If so, then we should get that in 0.10.1 or so asap...

**Comment by tony5** [comment] 2015-07-09 16:24
although downloading 8.1 from downloaded version 8.1 from https://github.com/owncloud/documents/releases works for me I get the error  Undefined index: REQUEST_URI at /var/www/cloud/apps/documents/appinfo/app.php#49  when cron runs. this look like the same error with the contacts app. https://github.com/owncloud/contacts/issues/972

**Comment by karlitschek** [comment] 2015-07-09 16:55
the latest is no published

**Closed by karlitschek** 2015-07-09 16:55 UTC

**Comment by shaneonabike** [comment] 2015-07-09 18:32
I can confirm that 8.1RC2 works now but it seems strange because when I tried it the first time it didnt. Perhaps I had the wrong permissions I am not certain.

**Comment by jospoortvliet** [comment] 2015-07-10 09:21
@shaneonabike note that there is a problem with upgrading apps where you essentially simply have to re-try by reloading the app store and upgrading again...

**Comment by Schmaetz** [comment] 2015-07-11 10:07
Hey there, just get a problem with Documents. 
Bevor the update comes out, i had the same problems like on the top. 
But after the update, i active the app in the app manager, then reload the side and the documents don't appear by apps. When i take a look back in the app manager the documents app still deactive.

i tried to remove the folder and install it again, same problem.

Someone now a how to for this?
Many greetings,
Matthias

**Comment by RealRancor** [comment] 2015-07-11 10:08
@Schmaetz See https://github.com/owncloud/documents/issues/508#issuecomment-120249639

**Comment by Schmaetz** [comment] 2015-07-11 10:24
Thanks for you answer. 
I downloaded the file in the topic #508, but it's still the same problem. 
I click on active, reload the site an the app still deactive.
Is there may a problem with the permissions?
Owner is www-data like the complete folder apps. 
The Problem is just with documents. Other Apps are no Problem.

Many greetings,
Matthias

**Comment by niandubay** [comment] 2015-07-13 00:02
same as Schmaetz , document app don't appear by apps. Other apps no problem.

**Comment by RealRancor** [comment] 2015-07-13 08:14
Please follow https://github.com/owncloud/documents/issues/508 as the original issue here was solved.

**Comment by niandubay** [comment] 2015-07-13 18:58
1 - uninstall application (which is broken) using applications panel
2 - delete the documents folder, if present on the server
3 - download file in https://apps.owncloud.com/content/show.php/Documents?content=168711
4 - unzip & paste this folder files in the apps folder but change the name to documents
5 - run the update process when accessing your owncloud
6 - activate the app in the "not active" category

That has worked for me.
(apologize for the bad language)

**Comment by djtm** [comment] 2015-07-17 10:38
Just FYI: In my case I had only the a few buttons show up but the webpage was stuck otherwise. The issue went away when not using opera as the browser. (firefox and chrome - though the latter is the same webkit engine - both work)

**Comment by Schmaetz** [comment] 2015-07-20 09:10
Thanks @niandubay 
it works :)

**Comment by Thomanji** [comment] 2015-07-30 11:17
All works fine for me too after manually puttong on 8.1 Beta1.
Is it correct that it can not handle .RTF, .DOC and .DOCX?

**Comment by RealRancor** [comment] 2015-07-30 14:00
.doc and .docx needs an extra config like described here:

https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/collaborative_documents_configuration.html
