### ISSUE TITLE
No vertical scrollbar when editing documents 

### ISSUE THREAD

**Issue by despens** [owncloud/documents#548] opened 2015-09-13 15:50 UTC
### Steps to reproduce
1. Open ODT document from either Documents app or Files
2. Multi-page document displayed without vertical scrollbar
3. Scrolling possible via moving the editing cursor around in the document.

### Expected behaviour
There should be a scrollbar visible.

### Actual behaviour
No scrollbar is visible at any time.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** MySQL, 5.5.44-0ubuntu0.14.04.1 (Ubuntu)

**PHP version:** PHP 5.5.9-1ubuntu4.11

**ownCloud version:** 8.1.1 (stable)

**Updated from an older ownCloud or fresh install:** Updated from 7.4

**List of activated apps:** Files, Activity, Pictures, Calendar, Contacts

**The content of config/config.php:**
```php
<?php
$CONFIG = array (
  'instanceid' => 'nope',
  'passwordsalt' => 'nope',
  'datadirectory' => '/var/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'nope',
  'dbhost' => 'nope',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nope',
  'dbpassword' => 'nope',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'forcessl' => true,
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'nope,
    1 => 'nope',
  ),
  'secret' => 'nope',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\OpenDocument',
    4 => 'OC\\Preview\\PDF',
    5 => 'OC\\Preview\\SVG',
  ),
  'memcache.local' => '\\OC\\Memcache\\APC',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
);
```

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Firefox 40.0.3

**Operating system:** Ubuntu 14.04

#### Web server error log
```
n/a
```

#### ownCloud log (data/owncloud.log)
```
n/a
```

#### Browser log
```
n/a
```

**Comment by glesik** [comment] 2015-10-30 18:32
Does resizing browser window help restore the scrollbar? If yes, this may be the duplicate of #538.

**Comment by jancborchardt** [comment] 2016-01-20 10:39
Closing as duplicate of https://github.com/owncloud/documents/issues/538

**Closed by jancborchardt** 2016-01-20 10:39 UTC
Labels: bug
