### ISSUE TITLE
"Save new documents to" setting is ignored

### ISSUE THREAD

**Issue by aarpon** [owncloud/documents#611] opened 2016-02-28 09:40 UTC
When I specify a folder in the "Save new documents to" field, the folder is created successfully if it does not exist (meaning that what I type seems to make sense), but then it is ignored. New files are alsways created in the root folder and if I go back to the settings it looks like the selection did not persist and the field is empty again.
Owncloud 8.2.2 using Documents 0.11.1.

**Comment by VicDeo** [comment] 2016-02-28 13:45
Duplicate of https://github.com/owncloud/documents/issues/600

**Closed by VicDeo** 2016-02-28 13:45 UTC
