### ISSUE TITLE
Cooperative edit does not work, ASSERTION FAILED 

### ISSUE THREAD

**Issue by crysman** [owncloud/documents#524] opened 2015-08-04 15:49 UTC
The app states that it supports:
- Cooperative edit, with multiple users editing files simultaneously.

But not in our case.

When I try to edit the file with another user simultaneously, js alert pops up with something like

>ASSERTION FAILED Inserting local cursor second time

error

Also, I am unable to close the file - an "ASSERTION FAILED tried to unsubscribe unknown callback..." error.

What might be the problem, please?

using ownCLoud 8.0.4 (stable)

**Comment by VicDeo** [comment] 2015-08-21 17:30
@crysman I don't see any reason for this :/ 
Which browsers are used by each user?

**Comment by VicDeo** [comment] 2015-09-01 16:18
@crysman please update the app to v0.9.1, clear browser cach and retry https://github.com/owncloud/documents/archive/stable8.zip

**Comment by VicDeo** [comment] 2015-09-02 13:56
Closing as a duplicate of https://github.com/owncloud/documents/issues/245 and https://github.com/owncloud/documents/issues/507

**Closed by VicDeo** 2015-09-02 13:56 UTC
