### ISSUE TITLE
Documents Preview Problem

### ISSUE THREAD

**Issue by lfratini** [owncloud/documents#521] opened 2015-08-03 11:28 UTC
I guys,

I can open Documents , but when i open a file type docx, doc ,, odt from app file i get this error

**Comment by lfratini** [comment] 2015-08-03 11:30
![owncloud8errror](https://cloud.githubusercontent.com/assets/10744873/9036628/8c80f314-39e3-11e5-90f2-eed84ca0a831.PNG)

**Comment by godemptiness** [comment] 2015-08-03 15:29
Double issue: https://github.com/owncloud/documents/issues/505

**Comment by VicDeo** [comment] 2015-08-04 11:24
Duplicate of https://github.com/owncloud/documents/issues/505 
Please track it there

**Closed by VicDeo** 2015-08-04 11:24 UTC
