### ISSUE TITLE
Unable to remove strikethrough

### ISSUE THREAD

**Issue by alleyoopster** [owncloud/documents#519] opened 2015-08-02 13:26 UTC
I am using a document created in ownCloud documents which is a list. Some are ~~strikethrough~~ items.

Try to remove strikethrough from word or phrase
### Steps to reproduce
1. highlighting text 
2. clicking strikethrough button

### Expected behaviour
The selected text should have the strikethrough removed

### Actual behaviour
On some text this does not work. It just creates and edited colour mark to the left, but strikethrough remains. 

### Server configuration
**Operating system**: Linux

**Web server:** Nginx

**Database:** mysql

**PHP version:** 5.6.9-0

**ownCloud version:** 8.1

**Updated from an older ownCloud or fresh install:** update

**List of activated apps:**

```Enabled:
 - activity: 2.0.1
 - contacts: 0.4.0.0
 - external: 1.2
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - mail: 0.1.3
 - provisioning_api: 0.2
 - templateeditor: 0.1
Disabled:
 - bookmarks
 - calendar
 - calendar.old
 - calendarplus
 - direct_menu
 - documents
 - encryption
 - files_encryption
 - music
 - ownnote
 - roundcube
 - search_lucene
 - shorty
 - storagecharts2
 - tasks
 - tasksplus
 - user_external
 - user_ldap
 - user_webdavauth


```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocpt5ctcvmoi',
  'passwordsalt' => '<secret>',
  'secret' => '<secret>',
  'trusted_domains' => 
  array (
    0 => 'cloud.kusikiliza.com',
  ),
  'datadirectory' => '/data/owncloud',
  'overwrite.cli.url' => 'https://cloud.kusikiliza.com',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_<secret>',
  'dbpassword' => '<secret>',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => '<secret>',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'gmail.com',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '<secret>',
  'mail_smtppassword' => '<secret>',
  'memcache.local' => '\\OC\\Memcache\\APCu',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 39.0

**Operating system:** Linux Mint 7.1 KDE

#### Web server error log
```
2015/08/01 09:42:59 [error] 27800#0: *11457 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 197.83.247.245, server: cloud.kusikiliza.com, request: "POST /index.php/apps/calendarplus/importeventscalendar HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock", host: "cloud.kusikiliza.com", referrer: "https://cloud.kusikiliza.com/index.php/apps/calendarplus/"
2015/08/01 09:52:14 [error] 27800#0: *11457 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 197.83.247.245, server: cloud.kusikiliza.com, request: "POST /index.php/apps/calendarplus/importeventscalendar HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock", host: "cloud.kusikiliza.com", referrer: "https://cloud.kusikiliza.com/index.php/apps/calendarplus/"
2015/08/01 10:17:15 [error] 27801#0: *12455 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 197.83.247.245, server: cloud.kusikiliza.com, request: "POST /index.php/apps/calendarplus/importeventscalendar HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock", host: "cloud.kusikiliza.com", referrer: "https://cloud.kusikiliza.com/index.php/apps/calendarplus/"
2015/08/01 18:41:23 [crit] 27802#0: *19909 SSL_do_handshake() failed (SSL: error:140A1175:SSL routines:SSL_BYTES_TO_CIPHER_LIST:inappropriate fallback) while SSL handshaking, client: 64.41.200.103, server: 0.0.0.0:443
2015/08/01 18:43:04 [crit] 27801#0: *20162 SSL_do_handshake() failed (SSL: error:14094085:SSL routines:SSL3_READ_BYTES:ccs received early) while SSL handshaking, client: 64.41.200.103, server: 0.0.0.0:443
2015/08/01 18:43:05 [crit] 27801#0: *20163 SSL_do_handshake() failed (SSL: error:14094085:SSL routines:SSL3_READ_BYTES:ccs received early) while SSL handshaking, client: 64.41.200.103, server: 0.0.0.0:443
2015/08/02 09:48:07 [error] 29020#0: *32306 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 62.210.250.116, server: cloud.kusikiliza.com, request: "GET /vtigercrm/vtigerservice.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "185.92.222.92"
2015/08/02 11:18:39 [error] 29018#0: *55129 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 197.87.145.61, server: cloud.kusikiliza.com, request: "PROPFIND /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.kusikiliza.com"
2015/08/02 12:36:39 [crit] 3765#0: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 197.87.145.61, server: cloud.kusikiliza.com, request: "PROPFIND /remote.php/caldav/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.kusikiliza.com"
2015/08/02 12:36:39 [crit] 3765#0: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 197.87.145.61, server: cloud.kusikiliza.com, request: "REPORT /remote.php/caldav/calendars/alleyoopster/contact_birthdays/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.kusikiliza.com"
2015/08/02 12:36:44 [error] 3765#0: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 197.87.145.61, server: cloud.kusikiliza.com, request: "REPORT /remote.php/caldav/calendars/alleyoopster/birthdays/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.kusikiliza.com"
2015/08/02 12:36:44 [crit] 3765#0: *49 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 197.87.145.61, server: cloud.kusikiliza.com, request: "REPORT /remote.php/caldav/calendars/alleyoopster/birthdays/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.kusikiliza.com"
2015/08/02 12:40:17 [crit] 3765#0: *257 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 197.87.145.61, server: cloud.kusikiliza.com, request: "PROPFIND /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.kusikiliza.com"

```

#### ownCloud log (data/owncloud.log)
```
EMPTY 
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by sndrr** [comment] 2015-09-07 06:58
I cannot reproduce this with a fresh install of v8.1.1.3.

**Comment by alleyoopster** [comment] 2015-09-07 08:43
Apologies for the information claiming Documents to be disabled. It is enabled and I am still seeing the problem. I am using owncloud 8.1.1 and documents 0.10.2. 

I have a just created a new document from within owncloud and typed this is a test on several new lines and tried highlighting lines and then applying strike-through. 

When trying to remove strike-through nothing happens. I highlight the line and click the box and the box remains selected (with a square around it) and the text does not change. This is very intermittent with some documents working and some not. I struggle to reproduce it. 

I have a document that is persistently broken. Would it benefit if I shared with you?

**Comment by sndrr** [comment] 2015-09-07 12:04
@alleyoopster Sure, I'll have a look. You can share it with sanderr@transfer.nkhn.nl.

**Comment by alleyoopster** [comment] 2015-09-07 12:21
@sndrr 
Error while sharing

Sharing failed, could not find sanderr@transfer.nkhn.nl, maybe the server is currently unreachable.

Maybe your federated sharing is not enabled to receive?

**Comment by sndrr** [comment] 2015-09-07 12:25
@alleyoopster It should work, but you can try sharing it with `sander@data.nkhn.nl` too.

**Comment by alleyoopster** [comment] 2015-09-07 12:29
@sndrr that worked, now shared

**Comment by sndrr** [comment] 2015-09-07 12:56
@alleyoopster Ok, I'm able to remove the ~~striketrough~~ after switching to another font and then back. Plus I found that the style of your document was set to `heading`.

**Comment by alleyoopster** [comment] 2015-09-07 13:03
It shows that it is set to Standard on mine, but when I changed to 
default style it seems to work.

**Comment by alleyoopster** [comment] 2015-09-07 14:27
@sndrr Thanks for your help with this. It is now working. Should I look this as a bug?

**Comment by sndrr** [comment] 2015-09-07 20:19
@alleyoopster Suppose this is a quirk that should be resolved, but it should also be repeatable. So I'd close the issue, but reopen it if it happens again in a reproducible way.

**Closed** 2015-09-08 13:00 UTC
Labels: bug
