### ISSUE TITLE
Set default folder with no whole owncloud search

### ISSUE THREAD

**Issue by apg1980** [owncloud/documents#549] opened 2015-09-16 08:50 UTC
Hello,

with the document app we can set an default directory to safe new docs. this is very helpful, but all the time the document app starts, it displays all documents from the owncloud account. is it possible to limit the displaying of documents to the set folder only?

best regards

**Comment by VicDeo** [comment] 2015-09-21 12:02
closing as a duplicate of https://github.com/owncloud/documents/issues/514

**Closed by VicDeo** 2015-09-21 12:02 UTC
