### ISSUE TITLE
Document takes Minutes to display, JS Error: Invalid time value

### ISSUE THREAD

**Issue by Georg-Git** [owncloud/documents#503] opened 2015-07-05 16:59 UTC
Add a new .odt Document.
Editing, Saving, Shared Public, Reopening, first everything is fine.

But after the document was opened for some times with different Browsers (Chrome, Firefox), opening the odt Documents takes Minutes.

At the same time JS Errors appears:
Chrome Console: "Uncaught RangeError: Invalid time value"
Firefox Firebug: "RangeError: invalid date"

Same place:
```javascript
function handleOperationExecuted(op) {
    var spec = op.spec(), memberId = spec.memberid, date = (new Date(spec.timestamp)).toISOString(), odfContainer = odfCanvas.odfContainer(), fullName;
...
```

No Errors or Warnings in OC Logs.

After deleting all rows in oc_documents_session, document is displayed as fast as lightning again - for some minutes...

New OC 8.0.4 installation, MySQL, No LDAP, Documents 0.9.0
Chrome 43.0.2357.130
Firefox 39.0

**Comment by VicDeo** [comment] 2015-08-25 18:50
@Georg-Git closing as a duplicate of https://github.com/owncloud/documents/issues/471
Fix: https://github.com/owncloud/documents/pull/533

**Closed by VicDeo** 2015-08-25 18:50 UTC
