### ISSUE TITLE
"No Connection to Server" after upgrade to OC8

### ISSUE THREAD

**Issue by olunet** [owncloud/documents#449] opened 2015-02-10 09:14 UTC
odt documents can not be opened. No error in the owncloud.log.
The error appeared after manual upgrade to OC8. After the upgrade the documents, calendar, bookmarks and contacts apps were missing. I downloaded them from apps.owncloud.com.
![error](https://cloud.githubusercontent.com/assets/526920/6124335/e296282e-b10c-11e4-82ca-f221d2d11366.png)

**Comment by rhanson-doyle** [comment] 2015-02-10 15:26
I am also having this problem. The log shows the following
`{"reqId":"26bd8c2e2a1d9b2da88a14b08655b694","remoteAddr":"192.xxx.x.xxx","app":"documents","message":"Error. Session no longer exists. No valid file has been passed","level":2,"time":"February 10, 2015 09:22:08","method":"POST","url":"\/owncloud\/index.php\/apps\/documents\/ajax\/otpoll.php"}`

**Comment by jkuchar** [comment] 2015-02-10 19:00
My installation is also affected: Error. Session no longer exists. No valid file has been passed in error log.

**Comment by jkuchar** [comment] 2015-02-10 20:40
And in firebug I see otpoll - HTTP bad request

**Comment by rhanson-doyle** [comment] 2015-02-10 21:29
I see the same bad request in chrome devtools

**Comment by VicDeo** [comment] 2015-02-11 20:31
is it reproducible for a newly created document?

**Comment by VicDeo** [comment] 2015-02-11 20:34
Manual upgrade assumes that everything except `config` and `data` directories was deleted from OC root directory.
Was `assets` directory left there for any chance?

**Comment by Luxiter** [comment] 2015-02-11 22:25
The problem is the cache of your browser, try to empty your browser cache and try again.
The code of the app is ok.
Tested in production enviroment after 2 day of debuging the our issue are solved with cleaning browser cache from users.

**Comment by jkuchar** [comment] 2015-02-11 22:26
Yes, when I create new document it does the same thing. (clicking new document button in documents App)

I've unpacked owncloud into emoty folder and then copied config and data, run upgrade rutine and then enabled documents module.

**Comment by jkuchar** [comment] 2015-02-11 22:30
@Luxiter Confirming, when I run browser in anonymous mode - it works. It looks like there was kept something broken in session or cookies. How can I help you with fixing this problem? Cookies and session storage dump?

**Comment by olunet** [comment] 2015-02-12 09:22
VicDeo: is it reproducible for a newly created document?

yes it is

VicDeo: Was assets directory left there for any chance?

no. The root directory was completely updated. Then the config and data were moved into it. Similar to what jkuchar wrote.

**Comment by rhanson-doyle** [comment] 2015-02-12 12:51
@Luxiter I can also confirm that the document editor works in private mode. Clearing my browser data fixed the issue completely. Thank you for your response.

**Comment by jkuchar** [comment] 2015-02-12 20:52
But actually this is not a solution. Cache should be always automatically purged on upgrade (eg. renaming all assets, etc.) However, shouldn't this be responsible of owncloud itself? (but I do not know how plugins in onwcloud are made)

**Comment by VicDeo** [comment] 2015-03-25 15:43
Documents app has nothing to do with caching of JS scripts and according to https://github.com/owncloud/core/issues/5936 fixed in core since OC8. 
Closing.

**Closed by VicDeo** 2015-03-25 15:43 UTC

**Comment by VicDeo** [comment] 2015-03-25 15:46
In case it is still reproducible please open an  issue  in core about regression referring to https://github.com/owncloud/core/issues/5936

**Comment by csarlanis** [comment] 2015-06-26 10:36
Dear All

If you enable in apache configuration 
mod_evasive
mod_security
can easily reproduce the problem.
