### ISSUE TITLE
Allow creating a document from the "+" button in Files

### ISSUE THREAD

**Issue by strugee** [owncloud/documents#590] opened 2015-11-24 03:20 UTC
In the Files app, there's a "+" button to create stuff. Currently it only has options for a text file, a folder, and uploading. Documents should insert something in that menu to allow creating a blank document.

I'm on ownCloud 8.2.1, Documents 0.11.0.

**Comment by VicDeo** [comment] 2015-11-24 16:49
Duplicate of https://github.com/owncloud/documents/issues/80

**Closed by VicDeo** 2015-11-24 16:49 UTC
Labels: enhancement
