### ISSUE TITLE
Unable to open documents

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/documents#477] opened 2015-05-06 04:20 UTC
When I click on a ODT file in the document app, wait some seconds until the toolbar appears but still see a white, empty screen, and hit the close button, then an alert dialog appears, saying just this:

```
ASSERTION FAILED:
editorSession should exist here.
```

**Comment by VicDeo** [comment] 2015-05-15 22:35
Looks like a duplicate of https://github.com/owncloud/documents/issues/458

**Comment by VicDeo** [comment] 2015-05-15 23:13
er... I thought I see an owncloud.log excerpt here

**Comment by binarykitchen** [comment] 2015-05-16 00:51
No, this was shown in an alert dialog (JavaScript: `alert(...)`). Nothing is written in the log.

**Comment by VicDeo** [comment] 2015-08-28 17:19
@binarykitchen closing as a duplicate of https://github.com/owncloud/documents/issues/490 
If it is still reproducible please post a detailed report (as per https://github.com/owncloud/documents/blob/master/CONTRIBUTING.md ) to
https://github.com/owncloud/documents/issues/490

**Closed by VicDeo** 2015-08-28 17:19 UTC
