### ISSUE TITLE
owncloud 8.1.1 document  0.10.1  document preview not working

### ISSUE THREAD

**Issue by wildhare3d** [owncloud/documents#537] opened 2015-08-26 21:29 UTC
When I try to the "apply and test" button I get the first error 1:
When I try to view a .doc file I get error 2:

1.
Warning	documents	Conversion test failed. Raw output:	2015-08-26T14:27:04+00:00
Error	PHP	Array to string conversion at /var/www/html/owncloud/lib/private/template/functions.php#36	2015-08-26T14:26:52+00:00

2.
Fatal	index	Exception: {"Exception":"RuntimeException","Message":"Empty conversion output","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/apps\/documents\/lib\/filter\/office.php(69): OCA\\Documents\\Converter::convert('???????????????...', 'odt:writer8', 'odt')\n#1 [internal function]: OCA\\Documents\\Filter\\Office->read(Array)\n#2 \/var\/www\/html\/owncloud\/apps\/documents\/lib\/filter.php(35): call_user_func(Array, Array)\n#3 \/var\/www\/html\/owncloud\/apps\/documents\/lib\/genesis.php(60): OCA\\Documents\\Filter::read('???????????????...', 'application\/msw...')\n#4 \/var\/www\/html\/owncloud\/apps\/documents\/controller\/documentcontroller.php(108): OCA\\Documents\\Genesis->__construct(Object(OCA\\Documents\\File))\n#5 [internal function]: OCA\\Documents\\Controller\\DocumentController->download('\/Ltr to DBaty 7...')\n#6 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Documents\\Controller\\DocumentController), 'download')\n#8 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Documents\\Controller\\DocumentController), 'download')\n#9 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('DocumentControl...', 'download', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/html\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/var\/www\/html\/owncloud\/lib\/base.php(873): OC\\Route\\Router->match('\/apps\/documents...')\n#13 \/var\/www\/html\/owncloud\/index.php(40): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/html\/owncloud\/apps\/documents\/lib\/converter.php","Line":26}

**Comment by VicDeo** [comment] 2015-09-02 14:14
@wildhare3d do you have a ssh access to this server?

**Comment by VicDeo** [comment] 2015-09-02 18:30
1. is opened in core https://github.com/owncloud/core/issues/17468


2. is a duplicate of https://github.com/owncloud/documents/issues/498 so let's continue there on this topic.
Closing as a duplicate

**Closed by VicDeo** 2015-09-02 18:30 UTC

**Comment by wildhare3d** [comment] 2015-09-02 22:26
Vic no SSH was not working, would that have caused the issue?

**Comment by wildhare3d** [comment] 2015-09-02 22:28
I am rebuilding the server from scratch to try and fix this. Do you have specific instructions on how to install either openOffice or libreOffice with OC 8.1.1 and Centos7 ?
