### ISSUE TITLE
Undefined method OC\\Log::warn using OC 8.2

### ISSUE THREAD

**Issue by Trefex** [owncloud/documents#596] opened 2015-12-06 21:24 UTC
When I choose Local in MS Support in Admin, the button gets stuck on "Saving" and nothing happens.

This is what is in the owncloud.log file. 

Does anybody know what I'm missing here?

{"reqId":"VmSl8bfEKTV2azujXFjhOwAAAAQ","remoteAddr":"10.74.0.14","app":"PHP","message":"Call to undefined method OC\\Log::warn() at \/var\/www\/html\/owncloud\/apps\/documents\/lib\/converter.php#42","level":3,"time":"2015-12-06T21:17:38+00:00"}

Thank you,
T

**Comment by VicDeo** [comment] 2015-12-07 13:39
@Trefex  duplicate of https://github.com/owncloud/documents/issues/576
Fixed with https://github.com/owncloud/documents/pull/578/files

**Comment by Trefex** [comment] 2015-12-07 19:07
HI @VicDeo,

When is this coming out? I am running 8.2.1 at the moment.

Best,

**Comment by VicDeo** [comment] 2015-12-07 20:20
@Trefex It's not aligned with ownCloud release since this is not a core app.  I have no distinct date atm.

**Comment by VicDeo** [comment] 2016-01-18 15:45
Released with Documents 0.11.1

**Closed by VicDeo** 2016-01-18 15:45 UTC
